---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - python-apt
          - apache2
        state: latest
    - name: Copy apache2.conf
      ansible.builtin.copy:
        src: files/config/apache2.conf
        dest: /etc/apache2/apache2.config
        owner: root
        group: root
        mode: "0644"
    - name: Copy index.html
      ansible.builtin.copy:
        src: files/site/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"
    - name: Create symbolic link
      ansible.builtin.file:
        src: /etc/apache2/mods-available/headers.load
        dest: /etc/apache2/mods-enabled/headers.load
        state : link
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
